#!/bin/bash
clear
# ----------------------------------------------
#      Advanced CPU Mining Script for Linux
# ----------------------------------------------
# Miner by: JayDDee;
# CREATED BY: 8TH;
# CREDITS: 8TH, Ecologyc & Devtechm;
# Project scheduled by: 8TH;
# Modified by: Devtechm;
# Faça uma pequena doação para o criador e programador deste projeto!
# Carteira BTC Dev1: 1Mzyt8ucJ1YW8JhQ6te13VWhoiEsTKhZF4
# Carteira BTC Dev2: 18kcsGYAn67jh34R3cjXP4v91azp1EApxs

# Este script foi desenvolvido para execução em ambiente Linux de 64 bits.
# Pode ser executado automaticamente junto com a inicialização do sistema.
# Funcional nas distros Debian e Ubuntu.

#--------------
# CPUMiner-OPT:
version=3.14.1
#--------------

funreboot () {
sudo apt-get install at -y > /dev/null
echo -e "Eliminando PIDS"
 for _pids_ in `atq | awk '{print $1}'`; do
 atrm $_pids_ > /dev/null 2>&1
 done
crontab -r
echo -e "Parando Processos"
 for pids in `ps x|grep -v grep|grep cpuminer`; do
 kill -9 pids > /dev/null 2>&1
 done
echo -e "Iniciando TIMER"
sudo touch /bin/cron
sudo chmod 777 /bin/cron
echo "#!/bin/bash" > /bin/cron
if [[ ${cpulimit} -gt "0" ]]; then
echo "sudo screen -dmS cpu cpulimit -e cpuminer -l ${cpulimit}" >> /bin/cron
fi
echo "sudo screen -dmS mining ./cpuminer -a ${algo} -o stratum+tcp://${str_tcp}${user}${pass}${core}" >> /bin/cron
echo "sleep ${rebo}m" >> /bin/cron
echo "at -f /bin/cron now + 2 min" >> /bin/cron
echo "sudo reboot" >> /bin/cron
sudo chmod 777 /bin/cron && bash /bin/cron & > /dev/null
}

funtimer () {
sudo apt-get install at -y > /dev/null
echo -e "Eliminando PIDS"
 for _pids_ in `atq | awk '{print $1}'`; do
 atrm $_pids_ > /dev/null 2>&1
 done
crontab -r
echo -e "Parando Processos"
 for pids in `ps x|grep -v grep|grep cpuminer`; do
 kill -9 pids > /dev/null 2>&1
 done
echo -e "Iniciando TIMER"
echo "#!/bin/bash" > /bin/cron
if [[ ${cpulimit} -gt "0" ]]; then
echo "sudo screen -dmS cpu cpulimit -e cpuminer -l ${cpulimit}" >> /bin/cron
fi
echo "sudo screen -dmS mining ./cpuminer -a ${algo} -o stratum+tcp://${str_tcp}${user}${pass}${core}" >> /bin/cron
echo "sleep ${timer}m" >> /bin/cron
echo 'for pids in $(ps x|grep -v grep|grep cpuminer); do' >> /bin/cron
echo 'kill -9 $pids' >> /bin/cron
echo 'screen -wipe' >> /bin/cron
echo 'done' >> /bin/cron
echo "at -f /bin/cron now + 4 min" >> /bin/cron
sudo chmod 777 /bin/cron && bash /bin/cron & > /dev/null
}

fun_help () {
echo -e "\033[1;31mMining SCP 8th\n\033[1;33mModo de uso!\nUtilize os parâmetros na execução do script!"
echo -e "\033[1;37m$0 -a 'algorithm' -s 'stratum+tcp' -u 'user' -p 'password'"
echo -e "\033[1;33mParâmetros adicionais:\n\033[1;37m-c 'core'\n-l 'cpulimit'\n-t 'timer'\n-r 'reboot'"
}

#/* -----------------------------------------------*/
#/* ------->>> INICIALIZANDO PARÂMETROS <<<--------*/
#/* -----------------------------------------------*/
entrada=($@)
for((nu=0; nu<${#entrada[@]}; nu++)); do
[[ ${entrada[$nu]} = @(-h|-H|-help|-Help) ]] && fun_help && exit 0
[[ ${entrada[$nu]} = @(-a|-A|-Alg|-alg) ]] && algorithm=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-s|-S|-Str|-str) ]] && stratum=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-u|-U|-Usr|-usr) ]] && user=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-p|-P|-Pwd|-pwd) ]] && password=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-c|-C|-Cor|-cor) ]] && core=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-l|-L|-Cpu|-cpu) ]] && cpulimit=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-t|-T|-Tim|-tim) ]] && timer=${entrada[$(($nu+1))]}
[[ ${entrada[$nu]} = @(-r|-R|-Reb|-reb) ]] && rebo=${entrada[$(($nu+1))]}
done
if [[ "$@" != "" ]]; then
echo -e "\033[1;31mIniciando procedimento com os seguintes parâmetros:\033[1;33m"
[[ "$(echo ${algorithm})" != "" ]] && echo -e "algorithm = ${algorithm}"
[[ "$(echo ${stratum})" != "" ]] && echo -e "stratum = ${stratum}"
[[ "$(echo ${user})" != "" ]] && echo -e "user = ${user}"
[[ "$(echo ${password})" != "" ]] && echo -e "password = ${password}"
[[ "$(echo ${core})" != "" ]] && echo -e "core = ${core}"
[[ "$(echo ${cpulimit})" != "" ]] && echo -e "cpulimit = ${cpulimit}"
[[ "$(echo ${timer})" != "" ]] && echo -e "timer/4 = ${timer}"
[[ "$(echo ${rebo})" != "" ]] && echo -e "mining/reboot = ${rebo}"
fi
echo -e "\033[1;31m---------------------------------------------------\033[1;33m \n"
sleep 5

#/* -----------------------------------------------*/
#/* -------->>> AVERIGUANDO PARÂMETROS <<<---------*/
#/* -----------------------------------------------*/
unset help
[[ "${help}" = "1" ]] && fun_help
[[ "$(echo ${algorithm})" != "" ]] && algo="${algorithm}"
[[ "$(echo ${stratum})" != "" ]] && str_tcp="${stratum}"
[[ "$(echo ${user})" != "" ]] && user=" -u ${user}"
[[ "$(echo ${password})" != "" ]] && pass=" -p ${password}"
[[ "$(echo ${core})" != "" ]] && core=" -t ${core}"
[[ "$(echo ${cpulimit})" = "" ]] && cpulimit="${cpulimit}"
[[ "$(echo ${timer})" = "" ]] && timer="${timer}"
unset help

#/* -----------------------------------------------*/
#/* ----------->>> INSTALANDO MINER <<<------------*/
#/* -----------------------------------------------*/
echo -e "\033[44;1;37m  Este script irá baixar, compilar e instalar o CPUMiner-OPT v${version}.  \033[0m"
echo -e "\033[44;1;37m            Ao término, a mineração iniciará automaticamente.              \033[0m"
sleep 10
clear

echo -e "\033[44;1;37mAtualizando lista de pacotes...\033[0m"
sudo apt-get update > /dev/null
sleep 2
clear

echo -e "\033[44;1;37mInstalando dependências...\033[0m"
apt-get install aptitude -y > /dev/null
sudo aptitude install cpulimit -y > /dev/null
sudo apt-get install screen -y > /dev/null
sudo apt-get install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev gcc autoconf make automake zlib1g-dev -y > /dev/null
memsize=`free | awk '/Mem/ { print $2 }'`
swapsize=`free | awk '/Swap/ { print $2 }'`
# Quando necessário cria uma partição SWAP de 1GB para máquinas com menos de 1GB de RAM.
if [ "$memsize" -lt "1000000" ]
then
 if [ "$swapsize" -eq "0" ]
 then
  echo -e "Foi detectado que você possui menos que 1GB de RAM!"
  echo -e "Será criada uma partição SWAP de 1GB para que o CPUMiner-OPT seja compilado com sucesso."
  sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000 > /dev/null
  sudo mkswap /var/swap.img > /dev/null
  sudo chmod 600 /var/swap.img
  sudo swapon /var/swap.img
 fi
fi
sleep 2
clear

echo -e "\033[44;1;37mBaixando CPUMiner-OPT v${version}...\033[0m"
wget -q https://github.com/JayDDee/cpuminer-opt/archive/v${version}.tar.gz
sleep 2
clear

echo -e "\033[44;1;37mExtraindo CPUMiner-OPT v${version}...\033[0m"
tar -zxvf v${version}.tar.gz > /dev/null
cd cpuminer-opt-${version}
sleep 2
clear

echo -e "\033[44;1;37mCompilando CPUMiner-OPT v${version}...(pode demorar um pouco)\033[0m"
./build.sh > /dev/null
# sudo cp cpuminer /usr/local/bin/
ln ./cpuminer ../cpuminer

#/* -----------------------------------------------*/
#/* ---------->>> INICIALIZANDO LIMIT <<<----------*/
#/* -----------------------------------------------*/
if [[ ${cpulimit} -gt "0" ]]; then
sudo screen -dmS cpu cpulimit -e cpuminer -l ${cpulimit}
fi
#/* -----------------------------------------------*/
#/* -------------->>> EXECUTANDO <<<---------------*/
#/* -----------------------------------------------*/
if [[ ${rebo} -gt "0" ]]; then
funreboot
elif [[ ${timer} -gt "0" ]]; then
funtimer
else
sudo screen -dmS mining ./cpuminer -a ${algo} -o stratum+tcp://${str_tcp}${user}${pass}${core}
fi
sleep 2
clear

echo -e "\033[44;1;37m Procedimento concluído e mineração iniciada! \033[0m"
echo -e "\033[44;1;37m Para visualizar o processo digite o comando: \033[0m"
echo -e "\033[44;1;37m               screen -x mining               \033[0m \n"
sleep 1
cd ..
sleep 1
sudo rm cpum
