#!/bin/sh -
clear
# Copyright: duferdias
# Contribution: AndreasBlk
# Miner by: JayDDee | CPUMiner-OPT v3.8.0.1

# Pools de mineração de Niobio Cash (Fev 2018)
# Definições
# ---------------------------------------------------
# altpools     » nbr.altpools.com
# stratum_tcp  » sv1.altpools.com:3334
# ---------------------------------------------------
# niobiopool   » niobiopool.com.br
# stratum_tcp  » niobiopool.com.br:3331
# ---------------------------------------------------
# niobiocashbb » niobiocash.bytecoinbrasil.net
# stratum_tcp  » niobiocash.bytecoinbrasil.net:3334
# ---------------------------------------------------
# selvahost    » nbr.selvahost.com.br
# stratum_tcp  » nb.selvahost.com.br:3333
# ---------------------------------------------------
# ciapool      » nbr.ciapool.com
# stratum_tcp  » nbr.ciapool.com:3333
# ---------------------------------------------------
# poolddns     » nbr-pool.ddns.net
# stratum_tcp  » nbr-pool.ddns.net:3333
# ---------------------------------------------------
# stminerpool  » stminerpool.com.br
# stratum_tcp  » stminerpool.com.br:3334
# ---------------------------------------------------
# 4miner       » nbr.4miner.me
# stratum_tcp  » us-nbr.4miner.me:3334
# ---------------------------------------------------

# Este script foi desenvolvido para execução em ambiente Linux.
# Pode ser executado automaticamente junto com a inicialização do sistema.

#-----------------
bash=$(echo $BASH)

if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

if [ "$1" = "altpools" ]
then
 stratum_tcp=sv1.altpools.com:3334
elif [ "$1" = "niobiopool" ]
then
 stratum_tcp=niobiopool.com.br:3331
elif [ "$1" = "niobiocashbb" ]
then
 stratum_tcp=niobiocash.bytecoinbrasil.net:3334
elif [ "$1" = "selvahost" ]
then
 stratum_tcp=nb.selvahost.com.br:3333
elif [ "$1" = "ciapool" ]
then
 stratum_tcp=nbr.ciapool.com:3333
elif [ "$1" = "poolddns" ]
then
 stratum_tcp=nbr-pool.ddns.net:3333
elif [ "$1" = "stminerpool" ]
then
 stratum_tcp=stminerpool.com.br:3334
elif [ "$1" = "4miner" ]
then
 stratum_tcp=us-nbr.4miner.me:3334
fi
wallet=$2
stratum_tcp_exemplo=stratum.miningpool:9999
carteira_exemplo=NBRyXXxx111YyyXXxx111YyyXXxx111YyyWYyyXXxx111YyyXXxx111YyyXXxx111YyyWYyyXXxx111YyyXXxx111YyyNBR


if [ "$1" = ""  ] && [ "$2" = ""  ]
then
echo "		\033[41;1;37m Minerar Niobio Cash com CPUMiner-OPT v3.8.0.1 \033[0m"				
sleep
echo "\033[34mForma de uso:\033[0m"
echo "sudo sh $0 \033[31m Endereço Stratum e Porta da Pool\033[32m Endereço da carteira de NBR\033[0m \n"
echo "\033[34mExemplo:\033[0m"
echo "sudo sh $0 \033[31m $stratum_tcp_exemplo\033[32m $carteira_exemplo\033[0m \n"
echo "\033[44;1;37m Observação:                                         \033[0m" 
echo "\033[44;1;37m O cpuminer-opt identifica automaticamente o tipo de \033[0m"
echo "\033[44;1;37m CPU e habilita todos os núcleos disponíveis para a  \033[0m"
echo "\033[44;1;37m mineração.                                          \033[0m \n"
exit 0
fi

echo "		\033[41;1;37m Minerar Niobio Cash com CPUMiner-OPT v3.8.0.1 \033[0m"	
sleep 1
echo "PARÂMETROS CONFIGURADOS:\033[01;32m $stratum_tcp $wallet\033[0m"
sleep 1
echo "\033[01;31mMinerar Niobio Cash com CPUMiner-OPT v3.8.0.1 $stratum_tcp\033[0m \n"
sleep 1
echo "\033[44;1;37m  Este script irá baixar, compilar e instalar o CPUMiner-OPT v3.8.0.1.  \033[0m"
echo "\033[44;1;37m           Ao término, a mineração iniciará automaticamente.            \033[0m"
sleep 10
clear

echo "\033[44;1;37mAtualizando lista de pacotes...\033[0m"
sudo apt-get update > /dev/null
sleep 2
clear

echo "\033[44;1;37mInstalando dependências...\033[0m"
sudo apt-get install screen -y > /dev/null
sudo apt-get install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev autoconf automake -y > /dev/null
memsize=`free | awk '/Mem/ { print $2 }'`
swapsize=`free | awk '/Swap/ { print $2 }'`
if [ "$memsize" -lt "1000000" ]
then
 if [ "$swapsize" -eq "0" ]
 then
  echo "Foi detectado que você possui menos que 1GB de RAM"
  echo "Será criada uma partição SWAP de 1GB para que o CPUMiner-OPT seja compilado com sucesso"
  sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000 > /dev/null
  sudo mkswap /var/swap.img > /dev/null
  sudo chmod 600 /var/swap.img
  sudo swapon /var/swap.img
 fi
fi
sleep 2
clear

echo "\033[44;1;37mBaixando CPUMiner-OPT v3.8.0.1...\033[0m"
wget -q https://github.com/JayDDee/cpuminer-opt/archive/v3.8.0.1.tar.gz
sleep 2
clear

echo "\033[44;1;37mExtraindo CPUMiner-OPT v3.8.0.1...\033[0m"
tar -zxvf v3.8.0.1.tar.gz > /dev/null
cd cpuminer-opt-3.8.0.1
sleep 2
clear

echo "\033[44;1;37mCompilando CPUMiner-OPT v3.8.0.1...(pode demorar um pouco)\033[0m"
./build.sh > /dev/null
ln ./cpuminer ../cpuminer
sleep 2
clear

echo "\033[01;32mInstalação e configuração concluídas com sucesso."
sleep 3
clear

echo "\033[44;1;37m       A mineração será iniciada em uma nova sessão.     \033[0m"
echo "\033[44;1;37m           NÃO FECHE A JANELA DO CONSOLE AGORA!          \033[0m"
echo "\033[44;1;37m     Feche a janela do web-console ou de seu aplicativo  \033[0m"
echo "\033[44;1;37m  para acesso remoto somente após o início da mineração. \033[0m \n"
sleep 5
echo "Acompanhe o status de sua mineração no endereço da pool escolhida."
echo "No campo abaixo de "Suas Estatísticas & Históricos de Pagamentos""
echo "insira sua carteira e clique no botão "Buscar" a direita."
sleep 15
clear

echo "\033[37;41mAbrindo sessão, aguarde...\033[0m"
sleep 3
sudo screen -dmS nbrmining ./cpuminer -a cryptonight -o stratum+tcp://$stratum_tcp -u $wallet -p x
sleep 2
clear

echo "\033[37;41mSua mineração foi iniciada! Para visualizar o processo digite o comando abaixo:\033[01;0m \n"
echo "\033[37;41mCOMANDO [screen -x nbrmining]\033[0m"
sleep 1
