#!/bin/sh
clear
# Script por Devtechm
# Referencias e Contribuições: AndreasBlk, Darkstilo e FENIX_LINUX
# Miner por JayDDee

# Contribua fazendo uma pequena doação!
# BTC:  18kcsGYAn67jh34R3cjXP4v91azp1EApxs
# DOGE: DBPkvRnTtHS84tSTyramL4CsYQcirqudhR

# Este script foi desenvolvido para execução em ambiente Linux de 64 bits:
# - Funcional nas distros Debian & Ubuntu;
# - A mineração funciona em todas as pools que usam os 
#   algorítimos suportados pelo cpuminer-opt;
# - O cpuminer-opt identifica automaticamente o tipo de CPU e
#   e habilita todos os núcleos disponíveis para a mineração;
# - Pode ser executado automaticamente junto com a inicialização
#   do sistema.

#-----------------
bash=$(echo $BASH)

if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

algorithm=$1
stratum_tcp=$2
user_w=$3
password=$4
algo_ex1=yescrypt
strat_ex1=mine.zpool.ca:6233
user_w_ex1=YyyXXxx111YyyXXxx111YyyXXxx111YyyW
pass_ex1=c=SIGLA
algo_ex2=yescryptr16
strat_ex2=stratum.misosi.ru:16012
user_w_ex2=webLogin.workerName
pass_ex2=x
#-----------------

#-----------------
# CPUMiner-OPT:
version=3.8.8.1
#-----------------


if [ "$1" = ""  ] && [ "$2" = ""  ] && [ "$3" = ""  ] && [ "$4" = ""  ]
then
echo "      \033[41;1;37m Minerar Criptomoedas com CPUMiner-OPT v$version \033[0m"
sleep
echo "\033[34mForma de uso:\033[0m"
echo "sudo sh $0 \033[31m Algorítimo\033[32m Stratum e Porta\033[32m Carteira ou usuário\033[32m Senha: verif. formato na pool\033[0m \n"
echo "\033[34mExemplo 1 - Zpool:\033[0m"
echo "sudo sh $0 \033[31m $algo_ex1\033[32m $strat_ex1\033[32m $user_w_ex1\033[32m $pass_ex1\033[0m \n"
echo "\033[34mExemplo 2 - Yenten Misosi Pool:\033[0m"
echo "sudo sh $0 \033[31m $algo_ex2\033[32m $strat_ex2\033[32m $user_w_ex2\033[32m $pass_ex2\033[0m \n"
echo "\033[44;1;37m Observação:                                         \033[0m" 
echo "\033[44;1;37m O cpuminer-opt identifica automaticamente o tipo de \033[0m"
echo "\033[44;1;37m CPU e habilita todos os núcleos disponíveis para a  \033[0m"
echo "\033[44;1;37m mineração.                                          \033[0m \n"
exit 0
fi

echo "      \033[41;1;37m Minerar Criptomoedas com CPUMiner-OPT v$version \033[0m"	
sleep 1
echo "PARÂMETROS CONFIGURADOS:\033[01;32m $algorithm $stratum_tcp $user_w $password\033[0m \n"
sleep 1
echo "\033[44;1;37m  Este script irá baixar, compilar e instalar o CPUMiner-OPT v$version.  \033[0m"
echo "\033[44;1;37m           Ao término, a mineração iniciará automaticamente.            \033[0m"
sleep 10
clear

echo "\033[44;1;37mAtualizando lista de pacotes...\033[0m"
sudo apt-get update > /dev/null
sleep 2
clear

echo "\033[44;1;37mInstalando dependências...\033[0m"
sudo apt-get install screen -y > /dev/null
sudo apt-get install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev gcc autoconf make automake -y > /dev/null
memsize=`free | awk '/Mem/ { print $2 }'`
swapsize=`free | awk '/Swap/ { print $2 }'`
if [ "$memsize" -lt "1000000" ]
then
 if [ "$swapsize" -eq "0" ]
 then
  echo "Foi detectado que você possui menos que 1GB de RAM!"
  echo "Será criada uma partição SWAP de 1GB para que o CPUMiner-OPT seja compilado com sucesso."
  sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000 > /dev/null
  sudo mkswap /var/swap.img > /dev/null
  sudo chmod 600 /var/swap.img
  sudo swapon /var/swap.img
 fi
fi
sleep 2
clear

echo "\033[44;1;37mBaixando CPUMiner-OPT v$version...\033[0m"
wget -q https://github.com/JayDDee/cpuminer-opt/archive/v$version.tar.gz
sleep 2
clear

echo "\033[44;1;37mExtraindo CPUMiner-OPT v$version...\033[0m"
tar -zxvf v$version.tar.gz > /dev/null
cd cpuminer-opt-$version
sleep 2
clear

echo "\033[44;1;37mCompilando CPUMiner-OPT v$version...(pode demorar um pouco)\033[0m"
./build.sh > /dev/null
ln ./cpuminer ../cpuminer
sleep 2
clear

echo "\033[01;32mInstalação e configuração concluídas com sucesso."
sleep 3
clear

echo "\033[44;1;37m       A mineração será iniciada em uma nova sessão.     \033[0m"
echo "\033[44;1;37m           NÃO FECHE A JANELA DO CONSOLE AGORA!          \033[0m"
echo "\033[44;1;37m     Feche a janela do web-console ou de seu aplicativo  \033[0m"
echo "\033[44;1;37m  para acesso remoto somente após o início da mineração. \033[0m"
sleep 15
clear

echo "\033[37;41mAbrindo sessão, aguarde...\033[0m"
sleep 3
sudo screen -dmS mining ./cpuminer -a $algorithm -o stratum+tcp://$stratump_tcp -u $user_w -p $password
sleep 2
clear

echo "\033[37;41mSua mineração foi iniciada! Para visualizar o processo digite o comando abaixo:\033[01;0m \n"
echo "\033[37;41mCOMANDO [screen -x mining]\033[0m"
sleep 1
sudo rm -r installm > /dev/null
